language: python
env:
  - TOX_ENV=py25-1.4
  - TOX_ENV=py26-1.4
  - TOX_ENV=py26-1.5
  - TOX_ENV=py27-1.4
  - TOX_ENV=py27-1.5
  - TOX_ENV=py27-trunk
  - TOX_ENV=pypy-1.4
before_install:
  - export PIP_USE_MIRRORS=true
  - export PIP_INDEX_URL=https://simple.crate.io/
  - export DJANGO_SETTINGS_MODULE=test_settings
  - sudo pip install tox
script:
  - tox -e $TOX_ENV
branches:
  only:
    - master
