language: python
env:
  - TOX_ENV=py26-15
  - TOX_ENV=py26-16
  - TOX_ENV=py27-15
  - TOX_ENV=py27-16
  - TOX_ENV=py27-17
  - TOX_ENV=py27-17-postgres
  - TOX_ENV=pypy-15
  - TOX_ENV=pypy-16
  - TOX_ENV=pypy-17
  - TOX_ENV=py32-16
  - TOX_ENV=py32-17
  - TOX_ENV=py33-16
  - TOX_ENV=py33-17
  - TOX_ENV=py34-16
  - TOX_ENV=py34-17
  - TOX_ENV=py34-17-postgres
before_install:
  - export PIP_USE_MIRRORS=true
  - export DJANGO_SETTINGS_MODULE=test_settings
  - sudo pip install tox
  - sudo apt-get install postgresql postgresql-client
  - # Password is 'sortedm2m'
  - echo "CREATE ROLE sortedm2m PASSWORD 'md5ba287bde612ca41b14776ec8f8dfdaa9' SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;" | sudo -u postgres psql
  - echo "CREATE DATABASE sortedm2m OWNER sortedm2m;" | sudo -u postgres psql
script:
  - tox -e $TOX_ENV -v
branches:
  only:
    - master
